export const GAS_TRANSMISSION_MODAL_FIELDS = [
  {
    definition: `Ne<sup>N</sup>`,
    label: `Номінальна потужність ГТУ`,
    id: `custom-nominal-power`,
    placeholder: `25000`,
    min: `4000`,
    max: `30000`,
    step: `1`,
    dimension: `кВт`,
    isTriple: false,
  },
  {
    definition: `T<sub>з</sub><sup>N</sup>`,
    label: `Номінальна температура повітря на вході в ГТУ`,
    id: `custom-nominal-temperature`,
    placeholder: `288`,
    min: `270`,
    max: `310`,
    step: `1`,
    dimension: `К`,
    isTriple: false,
  },
  {
    definition: `К<sub>N</sub>`,
    label: `Коефіцієнт, що враховує технічний стан ГТУ`,
    id: `custom-tech-state`,
    placeholder: `0.85`,
    min: `0.5`,
    max: `1`,
    step: `0.01`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `К<sub>t</sub>`,
    label: `Коефіцієнт, що враховує вплив температури атм. повітря`,
    id: `custom-air-impact`,
    placeholder: `3.2`,
    min: `1`,
    max: `6`,
    step: `0.01`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `η<sub>м</sub>`,
    label: `Механічний ККД нагнітача`,
    id: `custom-mech-efficiency`,
    placeholder: `0.95`,
    min: `0.6`,
    max: `1`,
    step: `0.001`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `q<sub>пг</sub><sup>N</sup>`,
    label: `Номінальна витрата паливного газу`,
    id: `custom-fuel-consumption`,
    placeholder: `3.28`,
    min: `1`,
    max: `15`,
    step: `0.01`,
    dimension: `тис. м<sup>3</sup>/д`,
    isTriple: false,
  },
  {
    definition: `Р<sub>доп</sub>`,
    label: `Кінцений тиск при виході з нагнітального патрубка`,
    id: `custom-pressure-allow`,
    placeholder: `7.45`,
    min: `4`,
    max: `8`,
    step: `0.001`,
    dimension: `МПа`,
    isTriple: false,
  },
  {
    definition: `ε`,
    label: `Ступінь підвищення тиску`,
    id: `custom-pressure-boost`,
    placeholder: `1.44`,
    min: `1`,
    max: `2`,
    step: `0.001`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `n<sub>ном</sub>`,
    label: `Номінальна обертова частота ротора`,
    id: `custom-nominal-rotate`,
    placeholder: `6500`,
    min: `2000`,
    max: `15000`,
    step: `1`,
    dimension: `об/хв`,
    isTriple: false,
  },
  {
    definition: `z<sub>зв</sub>`,
    label: `Коефіцієнт стисливості газу при якому побудовані зведені газодинамічні характеристики нагнітача`,
    id: `custom-zzv`,
    placeholder: `0.888`,
    min: `0.6`,
    max: `1`,
    step: `0.001`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `Т<sub>зв</sub>`,
    label: `Температура газу на вході при якій побудовані зведені газодинамічні характеристики нагнітача`,
    id: `custom-tzv`,
    placeholder: `288`,
    min: `260`,
    max: `320`,
    step: `0.1`,
    dimension: `К`,
    isTriple: false,
  },
  {
    definition: `R<sub>зв</sub>`,
    label: `Газова стала при якій побудовані зведені газодинамічні характеристики нагнітача`,
    id: `custom-rzv`,
    placeholder: `508`,
    min: `400`,
    max: `650`,
    step: `0.1`,
    dimension: `Дж/(кг·К)`,
    isTriple: false,
  },
  {
    definition: `Q<sub>зв</sub><sup>min</sup>`,
    label: `Мінімальне значення зведеної продуктивності за умов входу`,
    id: `custom-qzvmin`,
    placeholder: `200`,
    min: `50`,
    max: `1000`,
    step: `0.1`,
    dimension: `м<sup>3</sup>/хв`,
    isTriple: false,
  },
  {
    definition: `Q<sub>зв</sub><sup>max</sup>`,
    label: `Максимальне значення зведеної продуктивності за умов входу`,
    id: `custom-qzvmax`,
    placeholder: `500`,
    min: `50`,
    max: `1000`,
    step: `0.1`,
    dimension: `м<sup>3</sup>/хв`,
    isTriple: false,
  },
  {
    definition: `[n/n<sub>н</sub>]<sub>зв</sub><sup>min</sup>`,
    label: `Мінімальне значення зведених відносних обертів нагнітача`,
    id: `custom-nnzvmin`,
    placeholder: `0.8`,
    min: `0.5`,
    max: `1.3`,
    step: `0.01`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `[n/n<sub>н</sub>]<sub>зв</sub><sup>max</sup>`,
    label: `Максимальне значення зведених відносних обертів нагнітача`,
    id: `custom-nnzvmax`,
    placeholder: `1.05`,
    min: `0.8`,
    max: `1.5`,
    step: `0.01`,
    dimension: ``,
    isTriple: false,
  },
  {
    definition: `Р<sub>вх</sub>`,
    label: `Тиск на вході в перший нагнітач`,
    id: `custom-inlet-pressure`,
    placeholder: [`6.08`, `4.97`, `4.32`],
    min: `3`,
    max: `8`,
    step: `0.001`,
    dimension: `МПа`,
    isTriple: true,
  },
  {
    definition: `ε`,
    label: `Номінальний ступінь підвищення тиску для мат. моделі`,
    id: `custom-eps`,
    placeholder: [`1.45`, `1.37`, `1.21`],
    min: `1`,
    max: `1.9`,
    step: `0.001`,
    dimension: ``,
    isTriple: true,
  },
  {
    definition: `η`,
    label: `Політропний ККД для мат. моделі`,
    id: `custom-eta`,
    placeholder: [`0.84`, `0.81`, `0.58`],
    min: `0.4`,
    max: `1`,
    step: `0.001`,
    dimension: ``,
    isTriple: true,
  },
  {
    definition: `[N<sub>i</sub>/ρ<sub>вх</sub>]<sub>зв</sub>`,
    label: `Зведена відносна внутрішня потужність для мат. моделі`,
    id: `custom-nizv`,
    placeholder: [`215`, `238`, `220`],
    min: `100`,
    max: `1000`,
    step: `0.1`,
    dimension: `кВт/(кг/м<sup>3</sup>)`,
    isTriple: true,
  },
  {
    definition: `q<sub>н</sub>`,
    label: `Номінальна продуктивнісь нагнітача`,
    id: `custom-nominal-consumption`,
    placeholder: `31.0`,
    min: `5`,
    max: `70`,
    step: `0.01`,
    dimension: `млн. м<sup>3</sup>/д`,
    isTriple: false,
  },
];
