export const GAS_INDOOR_INPUT_FIELDS = [
  {
    definition: `ΔР<sub>доп</sub>`,
    label: `Допустимий перепад тиску газу`,
    id: `allowable-pressure`,
    placeholder: `300`,
    min: `0`,
    max: `3000`,
    step: `1`,
    dimension: `Па`,
  },
  {
    definition: `Р<sub>п</sub>`,
    label: `Початковий надлишковий тиск газу`,
    id: `starting-pressure`,
    placeholder: `1600`,
    min: `0`,
    max: `5000`,
    step: `1`,
    dimension: `Па`,
  },
  {
    definition: `ρ<sub>н</sub>`,
    label: `Густина газу за нормальних умов`,
    id: `gas-density`,
    placeholder: `0.8350`,
    min: `0.5`,
    max: `1`,
    step: `0.001`,
    dimension: `кг/м<sup>3</sup>`,
  },
  {
    definition: `υ·10<sup>-6</sup>`,
    label: `Кінематична в'язкість газу за норм. умов`,
    id: `gas-viscosity`,
    placeholder: `12.39`,
    min: `10`,
    max: `15`,
    step: `0.001`,
    dimension: `м<sup>2</sup>/с`,
  },
  {
    definition: `n`,
    label: `Кількість ділянок руху газу`,
    id: `segments-amount`,
    placeholder: `10`,
    min: `1`,
    max: `30`,
    step: `1`,
    dimension: `шт`,
  },
  {
    definition: `k`,
    label: `Коефіцієнт перевантаження мережі`,
    id: `overload-factor`,
    placeholder: `1`,
    min: `0.01`,
    max: `2`,
    step: `0.01`,
    dimension: ``,
  },
  {
    definition: `Т<sub>ср</sub>`,
    label: `Середня температура газу в мережі`,
    id: `average-temperature`,
    placeholder: `12`,
    min: `-10`,
    max: `50`,
    step: `0.1`,
    dimension: `<sup>о</sup>С`,
  },
  {
    definition: `ε`,
    label: `Точність розрахунку`,
    id: `calc-accurance`,
    placeholder: `1`,
    min: `0.1`,
    max: `100`,
    step: `0.1`,
    dimension: `%`,
  },
  {
    definition: `Р<sub>бар</sub>`,
    label: `Атмосферний тиск`,
    id: `atmospheric-pressure`,
    placeholder: `101325`,
    min: `90000`,
    max: `110000`,
    step: `1`,
    dimension: `Па`,
  },
  {
    definition: `w<sub>max</sub>`,
    label: `Максимальна швидкість газу в мережі`,
    id: `gas-speed`,
    placeholder: `7`,
    min: `0.1`,
    max: `10`,
    step: `0.01`,
    dimension: `м/с`,
  },
  {
    definition: `Q<sub>cp</sub>`,
    label: `Значення усередненої витрати газу`,
    id: `gas-consumption`,
    placeholder: `11`,
    min: `0.1`,
    max: `50`,
    step: `0.001`,
    dimension: `м<sup>3</sup>/год`,
  },
];
