export const adaptIncomeDataToServer = (clientData) => ({
  rch4: +clientData.methane,
  rc2h6: +clientData.ethane,
  rc3h8: +clientData.propane,
  rc4h10: +clientData.butane,
  rc5h12: +clientData.pentane,
  rn2: +clientData.nitrogen,
  rco2: +clientData["carbon-dioxide"],
  n: +clientData["inhibitants-amount"],
  t0: +clientData["temperature-for-heating"],
  tv: +clientData["temperature-for-venting"],
  tom: +clientData["temperature-avg-heating"],
  tvn: +clientData["temperature-inside"],
  n0: +clientData["heating-duration"],
  nkor: +clientData["cows-amount"],
  nkon: +clientData["horses-amount"],
  nsvin: +clientData["pigs-amount"],
  al1: +clientData["devices-gpcvg"] / 100,
  al2: +clientData["devices-gpvng"] / 100,
  al3: +clientData["devices-gp"] / 100,
  be1: +clientData["heating-device-gp"] / 100,
  be2: +clientData["heating-device-iok"] / 100,
  a1: +clientData["built-before-1985"] / 100,
  a2: +clientData["built-after-1985"] / 100,
  b1: +clientData["floor-1-2"] / 100,
  b2: +clientData["floor-3-4"] / 100,
  b3: +clientData["floor-high"] / 100,
});
