export const GAS_PHYSICS_INPUT_FIELDS = [
  {
    definition: `CH<sub>4</sub>`,
    label: `Метан`,
    id: `methane`,
    placeholder: `95.37`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>2</sub>H<sub>6</sub>`,
    label: `Етан`,
    id: `ethane`,
    placeholder: `2.63`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>3</sub>H<sub>8</sub>`,
    label: `Пропан`,
    id: `propane`,
    placeholder: `0.85`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>4</sub>H<sub>10</sub>`,
    label: `Н-бутан`,
    id: `butane`,
    placeholder: `0.27`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>5</sub>H<sub>12</sub>`,
    label: `Н-пентан`,
    id: `pentane`,
    placeholder: `0.07`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `N<sub>2</sub>`,
    label: `Азот`,
    id: `nitrogen`,
    placeholder: `0.62`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `CO<sub>2</sub>`,
    label: `Вуглекислий газ`,
    id: `carbon-dioxide`,
    placeholder: `0.19`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
];
