export const GAS_TRANSMISSION_INPUT_FIELDS = [
  {
    definition: `CH<sub>4</sub>`,
    label: `Метан`,
    id: `methane`,
    placeholder: `95.37`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>2</sub>H<sub>6</sub>`,
    label: `Етан`,
    id: `ethane`,
    placeholder: `2.63`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>3</sub>H<sub>8</sub>`,
    label: `Пропан`,
    id: `propane`,
    placeholder: `0.85`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>4</sub>H<sub>10</sub>`,
    label: `Н-бутан`,
    id: `butane`,
    placeholder: `0.27`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `C<sub>5</sub>H<sub>12</sub>`,
    label: `Н-пентан`,
    id: `pentane`,
    placeholder: `0.07`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `N<sub>2</sub>`,
    label: `Азот`,
    id: `nitrogen`,
    placeholder: `0.62`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `CO<sub>2</sub>`,
    label: `Вуглекислий газ`,
    id: `carbon-dioxide`,
    placeholder: `0.19`,
    min: `0`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `D<sub>з</sub>`,
    label: `Зовнішній діаметр газопроводу`,
    id: `diameter`,
    placeholder: `1420`,
    min: `530`,
    max: `1420`,
    step: null,
    dimension: `мм`,
  },
  {
    definition: `δ<sub>ст</sub>`,
    label: `Товщина стінки газопроводу`,
    id: `wall`,
    placeholder: `18.7`,
    min: `5`,
    max: `20`,
    step: `0.01`,
    dimension: `мм`,
  },
  {
    definition: `L`,
    label: `Довжина газопроводу`,
    id: `length`,
    placeholder: `128.4`,
    min: `50`,
    max: `170`,
    step: `0.01`,
    dimension: `км`,
  },
  {
    definition: `Q`,
    label: `Комерційна витрата газу на КС для першого наближення`,
    id: `consumption`,
    placeholder: `76.4`,
    min: `20`,
    max: `150`,
    step: `0.01`,
    dimension: `млн. м<sup>3</sup>/д`,
  },
  {
    definition: `E`,
    label: `Коефіцієнт гідравлічної ефективності газопроводу`,
    id: `hydraulic-coef`,
    placeholder: `95`,
    min: `1`,
    max: `100`,
    step: `0.01`,
    dimension: `%`,
  },
  {
    definition: `P<sub>атм</sub>`,
    label: `Атмосферний тиск`,
    id: `pressure-atm`,
    placeholder: `0.10`,
    min: `0.07`,
    max: `0.15`,
    step: `0.0001`,
    dimension: `МПа`,
  },
  {
    definition: `P<sub>вх</sub>`,
    label: `Абсолютний тиск газу на вході в нагнітачі КС`,
    id: `pressure-inlet`,
    placeholder: `5.25`,
    min: `2`,
    max: `7`,
    step: `0.001`,
    dimension: `МПа`,
  },
  {
    definition: `T<sub>вх</sub>`,
    label: `Температура газу на вході в нагнітачі КС`,
    id: `temperature-inlet`,
    placeholder: `18`,
    min: `0`,
    max: `50`,
    step: `0.1`,
    dimension: `°C`,
  },
  {
    definition: `T<sub>гр</sub>`,
    label: `Температура ґрунту в місці залягання газопроводу`,
    id: `temperature-ground`,
    placeholder: `16.6`,
    min: `-10`,
    max: `30`,
    step: `0.1`,
    dimension: `°C`,
  },
  {
    definition: `T<sub>атм</sub>`,
    label: `Температура повітря в районі розміщення КС`,
    id: `temperature-air`,
    placeholder: `20.7`,
    min: `-25`,
    max: `40`,
    step: `0.1`,
    dimension: `°C`,
  },
  {
    definition: `P<sub>к</sub>`,
    label: `Необхідний абсолютний тиск газу в кінці лінійної ділянки`,
    id: `pressure-end`,
    placeholder: `5.5`,
    min: `2`,
    max: `8`,
    step: `0.001`,
    dimension: `МПа`,
  },
  {
    definition: `K`,
    label: `Повний коефіцієнт теплопередачі від газу в навколишнє середовище`,
    id: `heat-coef`,
    placeholder: `1.754`,
    min: `0.1`,
    max: `5`,
    step: `0.001`,
    dimension: `Вт/(м<sup>2</sup>·К)`,
  },
  {
    type: `select`,
    id: `gpu-superchargers`,
    label: `Вибір газоперекачувального агрегату`,
    data: [
      {
        id: `gpu`,
        label: `Привід`,
        options: [
          {
            label: `ГТН-16`,
            value: `gtn-16`,
            compatibility: [`n-16-76-1.37`, `n-16-76-1.44`],
          },
          {
            label: `ГТК-10-4`,
            value: `gtk-10-4`,
            compatibility: [`235-21-1`],
          },
          {
            label: `ГТН-25`,
            value: `gtn-25`,
            compatibility: [`650-21-2`, `650-22-2`],
          },
          {
            label: `НЦ-16/76-1,45`,
            value: `nc-16-76-1.45`,
            compatibility: [`gpa-c-16-76`],
          },
          {
            label: `ГТК-10И`,
            value: `gtk-10i`,
            compatibility: [`rf2bb-30`, `cdp-224`, `pcl-802-24`, `655-r2`],
          },
          {
            label: `ГТН-25И`,
            value: `gtn-25i`,
            compatibility: [`pcl-1002-40`],
          },
          {
            label: `ГТК-25И`,
            value: `gtk-25i`,
            compatibility: [`pcl-804-2`],
          },
          {
            label: `Інший`,
            value: `custom`,
            compatibility: [`custom`],
          },
        ],
      },
      {
        id: `supercharger`,
        label: `Нагнітач`,
        options: [
          {
            label: `Н-16-76-1,37`,
            value: `n-16-76-1.37`,
            compatibility: [`gtn-16`],
          },
          {
            label: `Н-16-76-1,44`,
            value: `n-16-76-1.44`,
            compatibility: [`gtn-16`],
          },
          {
            label: `235-21-1`,
            value: `235-21-1`,
            compatibility: [`gtk-10-4`],
          },
          {
            label: `650-21-2`,
            value: `650-21-2`,
            compatibility: [`gtn-25`],
          },
          {
            label: `650-22-2`,
            value: `650-22-2`,
            compatibility: [`gtn-25`],
          },
          {
            label: `ГПА-Ц-16/76`,
            value: `gpa-c-16-76`,
            compatibility: [`nc-16-76-1.45`],
          },
          {
            label: `RF2BB-30`,
            value: `rf2bb-30`,
            compatibility: [`gtk-10i`],
          },
          {
            label: `CDP-224`,
            value: `cdp-224`,
            compatibility: [`gtk-10i`],
          },
          {
            label: `PCL-802/24`,
            value: `pcl-802-24`,
            compatibility: [`gtk-10i`],
          },
          {
            label: `PCL-1002/40`,
            value: `pcl-1002-40`,
            compatibility: [`gtn-25i`],
          },
          {
            label: `PCL-804-2`,
            value: `pcl-804-2`,
            compatibility: [`gtk-25i`],
          },
          {
            label: `655 P2`,
            value: `655-r2`,
            compatibility: [`gtk-10i`],
          },
          {
            label: `Інший`,
            value: `custom`,
            compatibility: [`custom`],
          },
        ],
      },
    ],
  },
];
