export const GAS_BRANCHES_INPUT_FIELDS = [
  {
    definition: `ρ<sub>н</sub>`,
    label: `Густина природного газу за нормальних умов`,
    id: `normalDensity`,
    placeholder: `0.835`,
    min: `0.1`,
    max: `1`,
    step: `0.0001`,
    dimension: `кг/м<sup>3</sup>`,
    pressureType: `BOTH`,
    calcType: `BOTH`,
  },
  {
    definition: `υ·10<sup>-6</sup>`,
    label: `Кінематична в'язкість природного газу`,
    id: `kinematicViscosity`,
    placeholder: `12.39`,
    min: `10`,
    max: `15`,
    step: `0.01`,
    dimension: `м<sup>2</sup>/с`,
    pressureType: `BOTH`,
    calcType: `BOTH`,
  },
  {
    definition: `ΔP<sub>доп</sub>`,
    label: `Допустимі втрати тиску в мережі`,
    id: `pressure-drop`,
    placeholder: `1200`,
    min: `500`,
    max: `3000`,
    step: `1`,
    dimension: `Па`,
    pressureType: `LOW`,
    calcType: `BOTH`,
  },
  {
    definition: `k<sub>п</sub>`,
    label: `Коефіцієнт перевантаження мережі`,
    id: `highload-coef`,
    placeholder: `1`,
    min: `1`,
    max: `1.5`,
    step: `0.01`,
    dimension: ``,
    pressureType: `LOW`,
    calcType: `BOTH`,
  },
  {
    definition: `P<sub>п</sub>`,
    label: `Надлишковий тиск газу на початку газової мережі`,
    id: `pressure-start-low`,
    placeholder: `3000`,
    min: `2000`,
    max: `5000`,
    step: `1`,
    dimension: `Па`,
    pressureType: `LOW`,
    calcType: `ROUTE`,
  },
  {
    definition: `n<sub>о</sub>`,
    label: `Кількість ділянок напряму руху газу`,
    id: `routes-amount`,
    placeholder: `1`,
    min: `1`,
    max: `10`,
    step: `1`,
    dimension: `шт`,
    pressureType: `BOTH`,
    calcType: `ROUTE`,
  },
  {
    definition: `P<sub>п</sub>`,
    label: `Абсолютний тиск газу на початку`,
    id: `pressure-start-medium`,
    placeholder: `0.3`,
    min: `0.2`,
    max: `0.6`,
    step: `0.001`,
    dimension: `МПа`,
    pressureType: `MEDIUM`,
    calcType: `BOTH`,
  },
  {
    definition: `P<sub>к</sub>`,
    label: `Мінімально допустимий тиск в кінці`,
    id: `pressure-end-medium`,
    placeholder: `0.2`,
    min: `0.1`,
    max: `0.4`,
    step: `0.001`,
    dimension: `МПа`,
    pressureType: `MEDIUM`,
    calcType: `BOTH`,
  },
];
